// Generate TypeScript types for the public schema via the Management API and write src/lib/database.types.ts.
// Usage (after dot-sourcing secrets.ps1): node --env-file=.env.local scripts/db/gen-types.mjs
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const ref = process.env.SUPABASE_PROJECT_REF || "fboythglcjofakbskstg";
const token = process.env.SUPABASE_ACCESS_TOKEN;
if (!token) {
  console.error("SUPABASE_ACCESS_TOKEN missing (dot-source secrets.ps1 first)");
  process.exit(2);
}

let lastErr;
for (let attempt = 1; attempt <= 4; attempt++) {
  try {
    const res = await fetch(`https://api.supabase.com/v1/projects/${ref}/types/typescript?included_schemas=public`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    const body = await res.json();
    if (!res.ok || typeof body.types !== "string") throw new Error(`HTTP ${res.status}: ${JSON.stringify(body).slice(0, 300)}`);
    const header =
      "// AUTO-GENERATED by scripts/db/gen-types.mjs from the live Supabase schema. Do not edit by hand.\n" +
      "// Regenerate: node --env-file=.env.local scripts/db/gen-types.mjs\n\n";
    const out = join(process.cwd(), "src", "lib", "database.types.ts");
    writeFileSync(out, header + body.types, "utf8");
    console.log(`wrote ${out} (${body.types.length} chars)`);
    process.exit(0);
  } catch (e) {
    lastErr = e;
    console.error(`attempt ${attempt} failed: ${e.message}`);
    await new Promise((r) => setTimeout(r, 2000 * attempt));
  }
}
console.error(lastErr?.message);
process.exit(1);
