// AUTO-GENERATED by scripts/db/gen-types.mjs from the live Supabase schema. Do not edit by hand.
// Regenerate: node --env-file=.env.local scripts/db/gen-types.mjs

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      announcements: {
        Row: {
          body: string | null
          created_at: string
          created_by: string | null
          ends_at: string | null
          id: string
          is_demo: boolean
          kind: string
          neighbourhood_ids: string[]
          source_label: string | null
          starts_at: string
          title: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          created_by?: string | null
          ends_at?: string | null
          id?: string
          is_demo?: boolean
          kind?: string
          neighbourhood_ids?: string[]
          source_label?: string | null
          starts_at?: string
          title: string
        }
        Update: {
          body?: string | null
          created_at?: string
          created_by?: string | null
          ends_at?: string | null
          id?: string
          is_demo?: boolean
          kind?: string
          neighbourhood_ids?: string[]
          source_label?: string | null
          starts_at?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "announcements_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "announcements_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      app_settings: {
        Row: {
          key: string
          updated_at: string
          value: Json
        }
        Insert: {
          key: string
          updated_at?: string
          value: Json
        }
        Update: {
          key?: string
          updated_at?: string
          value?: Json
        }
        Relationships: []
      }
      business_documents: {
        Row: {
          business_id: string
          created_at: string
          id: string
          kind: string
          path: string
        }
        Insert: {
          business_id: string
          created_at?: string
          id?: string
          kind?: string
          path: string
        }
        Update: {
          business_id?: string
          created_at?: string
          id?: string
          kind?: string
          path?: string
        }
        Relationships: [
          {
            foreignKeyName: "business_documents_business_id_fkey"
            columns: ["business_id"]
            isOneToOne: false
            referencedRelation: "businesses"
            referencedColumns: ["id"]
          },
        ]
      }
      business_photos: {
        Row: {
          business_id: string
          created_at: string
          id: string
          sort: number
          url: string
        }
        Insert: {
          business_id: string
          created_at?: string
          id?: string
          sort?: number
          url: string
        }
        Update: {
          business_id?: string
          created_at?: string
          id?: string
          sort?: number
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "business_photos_business_id_fkey"
            columns: ["business_id"]
            isOneToOne: false
            referencedRelation: "businesses"
            referencedColumns: ["id"]
          },
        ]
      }
      business_service_areas: {
        Row: {
          business_id: string
          neighbourhood_id: string
        }
        Insert: {
          business_id: string
          neighbourhood_id: string
        }
        Update: {
          business_id?: string
          neighbourhood_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "business_service_areas_business_id_fkey"
            columns: ["business_id"]
            isOneToOne: false
            referencedRelation: "businesses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "business_service_areas_neighbourhood_id_fkey"
            columns: ["neighbourhood_id"]
            isOneToOne: false
            referencedRelation: "neighbourhoods"
            referencedColumns: ["id"]
          },
        ]
      }
      business_service_categories: {
        Row: {
          business_id: string
          category_id: string
        }
        Insert: {
          business_id: string
          category_id: string
        }
        Update: {
          business_id?: string
          category_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "business_service_categories_business_id_fkey"
            columns: ["business_id"]
            isOneToOne: false
            referencedRelation: "businesses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "business_service_categories_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      businesses: {
        Row: {
          address: string | null
          approved_at: string | null
          category_label: string | null
          cover_url: string | null
          created_at: string
          description: string | null
          id: string
          is_demo: boolean
          kinds: string[]
          lat: number | null
          leads_accepted_count: number
          lng: number | null
          location: unknown
          logo_url: string | null
          name: string
          neighbourhood_id: string | null
          owner_id: string
          phone: string | null
          rating_avg: number
          rating_count: number
          rejection_reason: string | null
          search_norm: string | null
          slug: string
          status: string
          updated_at: string
          vacation_mode: boolean
          verification_level: number
          working_hours: Json
        }
        Insert: {
          address?: string | null
          approved_at?: string | null
          category_label?: string | null
          cover_url?: string | null
          created_at?: string
          description?: string | null
          id?: string
          is_demo?: boolean
          kinds?: string[]
          lat?: number | null
          leads_accepted_count?: number
          lng?: number | null
          location?: unknown
          logo_url?: string | null
          name: string
          neighbourhood_id?: string | null
          owner_id: string
          phone?: string | null
          rating_avg?: number
          rating_count?: number
          rejection_reason?: string | null
          search_norm?: string | null
          slug: string
          status?: string
          updated_at?: string
          vacation_mode?: boolean
          verification_level?: number
          working_hours?: Json
        }
        Update: {
          address?: string | null
          approved_at?: string | null
          category_label?: string | null
          cover_url?: string | null
          created_at?: string
          description?: string | null
          id?: string
          is_demo?: boolean
          kinds?: string[]
          lat?: number | null
          leads_accepted_count?: number
          lng?: number | null
          location?: unknown
          logo_url?: string | null
          name?: string
          neighbourhood_id?: string | null
          owner_id?: string
          phone?: string | null
          rating_avg?: number
          rating_count?: number
          rejection_reason?: string | null
          search_norm?: string | null
          slug?: string
          status?: string
          updated_at?: string
          vacation_mode?: boolean
          verification_level?: number
          working_hours?: Json
        }
        Relationships: [
          {
            foreignKeyName: "businesses_neighbourhood_id_fkey"
            columns: ["neighbourhood_id"]
            isOneToOne: false
            referencedRelation: "neighbourhoods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "businesses_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "businesses_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: true
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_events: {
        Row: {
          created_at: string
          event: string
          id: string
          ip_hash: string | null
          subject_id: string
          subject_type: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          event: string
          id?: string
          ip_hash?: string | null
          subject_id: string
          subject_type: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          event?: string
          id?: string
          ip_hash?: string | null
          subject_id?: string
          subject_type?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contact_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_messages: {
        Row: {
          created_at: string
          handled: boolean
          id: string
          message: string
          name: string | null
          phone: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string
          handled?: boolean
          id?: string
          message: string
          name?: string | null
          phone?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string
          handled?: boolean
          id?: string
          message?: string
          name?: string | null
          phone?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contact_messages_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_messages_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      demo_otp: {
        Row: {
          code: string
          created_at: string
          id: string
          phone: string
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          phone: string
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          phone?: string
        }
        Relationships: []
      }
      favorites: {
        Row: {
          created_at: string
          target_id: string
          target_type: string
          user_id: string
        }
        Insert: {
          created_at?: string
          target_id: string
          target_type: string
          user_id: string
        }
        Update: {
          created_at?: string
          target_id?: string
          target_type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "favorites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favorites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          accepted_at: string | null
          business_id: string
          created_at: string
          id: string
          match_score: number | null
          offer_note: string | null
          offer_price_try: number | null
          request_id: string
          seen_at: string | null
          status: string
          updated_at: string
          wave_no: number
        }
        Insert: {
          accepted_at?: string | null
          business_id: string
          created_at?: string
          id?: string
          match_score?: number | null
          offer_note?: string | null
          offer_price_try?: number | null
          request_id: string
          seen_at?: string | null
          status?: string
          updated_at?: string
          wave_no?: number
        }
        Update: {
          accepted_at?: string | null
          business_id?: string
          created_at?: string
          id?: string
          match_score?: number | null
          offer_note?: string | null
          offer_price_try?: number | null
          request_id?: string
          seen_at?: string | null
          status?: string
          updated_at?: string
          wave_no?: number
        }
        Relationships: [
          {
            foreignKeyName: "leads_business_id_fkey"
            columns: ["business_id"]
            isOneToOne: false
            referencedRelation: "businesses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "service_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_categories: {
        Row: {
          attributes_schema: Json
          created_at: string
          icon: string | null
          id: string
          is_banned: boolean
          name: string
          parent_id: string | null
          slug: string
          sort: number
          type: string
        }
        Insert: {
          attributes_schema?: Json
          created_at?: string
          icon?: string | null
          id?: string
          is_banned?: boolean
          name: string
          parent_id?: string | null
          slug: string
          sort?: number
          type: string
        }
        Update: {
          attributes_schema?: Json
          created_at?: string
          icon?: string | null
          id?: string
          is_banned?: boolean
          name?: string
          parent_id?: string | null
          slug?: string
          sort?: number
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "listing_categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "listing_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_media: {
        Row: {
          created_at: string
          id: string
          listing_id: string
          sort: number
          thumb_url: string | null
          url: string
        }
        Insert: {
          created_at?: string
          id?: string
          listing_id: string
          sort?: number
          thumb_url?: string | null
          url: string
        }
        Update: {
          created_at?: string
          id?: string
          listing_id?: string
          sort?: number
          thumb_url?: string | null
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "listing_media_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      listings: {
        Row: {
          attributes: Json
          business_id: string | null
          call_count: number
          category_id: string
          created_at: string
          description: string | null
          expires_at: string
          flags: string[]
          id: string
          is_demo: boolean
          job_benefits: string[]
          job_experience: string | null
          job_location_label: string | null
          job_salary_hidden: boolean
          job_salary_max: number | null
          job_salary_min: number | null
          job_work_type: string | null
          neighbourhood_id: string | null
          owner_id: string
          price_try: number | null
          published_at: string | null
          rejection_reason: string | null
          search_norm: string | null
          search_tsv: unknown
          status: string
          title: string
          type: string
          updated_at: string
          view_count: number
        }
        Insert: {
          attributes?: Json
          business_id?: string | null
          call_count?: number
          category_id: string
          created_at?: string
          description?: string | null
          expires_at?: string
          flags?: string[]
          id?: string
          is_demo?: boolean
          job_benefits?: string[]
          job_experience?: string | null
          job_location_label?: string | null
          job_salary_hidden?: boolean
          job_salary_max?: number | null
          job_salary_min?: number | null
          job_work_type?: string | null
          neighbourhood_id?: string | null
          owner_id: string
          price_try?: number | null
          published_at?: string | null
          rejection_reason?: string | null
          search_norm?: string | null
          search_tsv?: unknown
          status?: string
          title: string
          type: string
          updated_at?: string
          view_count?: number
        }
        Update: {
          attributes?: Json
          business_id?: string | null
          call_count?: number
          category_id?: string
          created_at?: string
          description?: string | null
          expires_at?: string
          flags?: string[]
          id?: string
          is_demo?: boolean
          job_benefits?: string[]
          job_experience?: string | null
          job_location_label?: string | null
          job_salary_hidden?: boolean
          job_salary_max?: number | null
          job_salary_min?: number | null
          job_work_type?: string | null
          neighbourhood_id?: string | null
          owner_id?: string
          price_try?: number | null
          published_at?: string | null
          rejection_reason?: string | null
          search_norm?: string | null
          search_tsv?: unknown
          status?: string
          title?: string
          type?: string
          updated_at?: string
          view_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "listings_business_id_fkey"
            columns: ["business_id"]
            isOneToOne: false
            referencedRelation: "businesses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "listing_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_neighbourhood_id_fkey"
            columns: ["neighbourhood_id"]
            isOneToOne: false
            referencedRelation: "neighbourhoods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      neighbourhoods: {
        Row: {
          center: unknown
          created_at: string
          district: string
          id: string
          lat: number | null
          lng: number | null
          name: string
          osm_id: number | null
          slug: string
        }
        Insert: {
          center?: unknown
          created_at?: string
          district?: string
          id?: string
          lat?: number | null
          lng?: number | null
          name: string
          osm_id?: number | null
          slug: string
        }
        Update: {
          center?: unknown
          created_at?: string
          district?: string
          id?: string
          lat?: number | null
          lng?: number | null
          name?: string
          osm_id?: number | null
          slug?: string
        }
        Relationships: []
      }
      news_items: {
        Row: {
          created_at: string
          guid: string
          id: string
          published_at: string | null
          source_id: string
          summary: string | null
          title: string
          title_hash: string | null
          url: string
        }
        Insert: {
          created_at?: string
          guid: string
          id?: string
          published_at?: string | null
          source_id: string
          summary?: string | null
          title: string
          title_hash?: string | null
          url: string
        }
        Update: {
          created_at?: string
          guid?: string
          id?: string
          published_at?: string | null
          source_id?: string
          summary?: string | null
          title?: string
          title_hash?: string | null
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "news_items_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "news_sources"
            referencedColumns: ["id"]
          },
        ]
      }
      news_sources: {
        Row: {
          active: boolean
          created_at: string
          feed_url: string
          id: string
          last_error: string | null
          last_fetched_at: string | null
          name: string
          site_url: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          feed_url: string
          id?: string
          last_error?: string | null
          last_fetched_at?: string | null
          name: string
          site_url: string
        }
        Update: {
          active?: boolean
          created_at?: string
          feed_url?: string
          id?: string
          last_error?: string | null
          last_fetched_at?: string | null
          name?: string
          site_url?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          link: string | null
          push_sent_at: string | null
          read_at: string | null
          title: string
          type: string
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          link?: string | null
          push_sent_at?: string | null
          read_at?: string | null
          title: string
          type: string
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          link?: string | null
          push_sent_at?: string | null
          read_at?: string | null
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pharmacy_duty: {
        Row: {
          duty_end: string
          duty_start: string
          fetched_at: string
          id: string
          note: string | null
          poi_id: string
          source: string
        }
        Insert: {
          duty_end: string
          duty_start: string
          fetched_at?: string
          id?: string
          note?: string | null
          poi_id: string
          source?: string
        }
        Update: {
          duty_end?: string
          duty_start?: string
          fetched_at?: string
          id?: string
          note?: string | null
          poi_id?: string
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "pharmacy_duty_poi_id_fkey"
            columns: ["poi_id"]
            isOneToOne: false
            referencedRelation: "poi"
            referencedColumns: ["id"]
          },
        ]
      }
      poi: {
        Row: {
          address: string | null
          created_at: string
          details: Json
          id: string
          kind: string
          lat: number | null
          license: string | null
          lng: number | null
          location: unknown
          name: string
          neighbourhood_id: string | null
          phone: string | null
          search_norm: string | null
          slug: string
          source: string
          source_ref: string | null
          updated_at: string
        }
        Insert: {
          address?: string | null
          created_at?: string
          details?: Json
          id?: string
          kind: string
          lat?: number | null
          license?: string | null
          lng?: number | null
          location: unknown
          name: string
          neighbourhood_id?: string | null
          phone?: string | null
          search_norm?: string | null
          slug: string
          source?: string
          source_ref?: string | null
          updated_at?: string
        }
        Update: {
          address?: string | null
          created_at?: string
          details?: Json
          id?: string
          kind?: string
          lat?: number | null
          license?: string | null
          lng?: number | null
          location?: unknown
          name?: string
          neighbourhood_id?: string | null
          phone?: string | null
          search_norm?: string | null
          slug?: string
          source?: string
          source_ref?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "poi_neighbourhood_id_fkey"
            columns: ["neighbourhood_id"]
            isOneToOne: false
            referencedRelation: "neighbourhoods"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          is_demo: boolean
          kvkk_accepted_at: string | null
          marketing_consent: boolean
          neighbourhood_id: string | null
          onboarded: boolean
          phone: string | null
          role: string
          status: string
          trusted_publisher: boolean
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          is_demo?: boolean
          kvkk_accepted_at?: string | null
          marketing_consent?: boolean
          neighbourhood_id?: string | null
          onboarded?: boolean
          phone?: string | null
          role?: string
          status?: string
          trusted_publisher?: boolean
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          is_demo?: boolean
          kvkk_accepted_at?: string | null
          marketing_consent?: boolean
          neighbourhood_id?: string | null
          onboarded?: boolean
          phone?: string | null
          role?: string
          status?: string
          trusted_publisher?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_neighbourhood_id_fkey"
            columns: ["neighbourhood_id"]
            isOneToOne: false
            referencedRelation: "neighbourhoods"
            referencedColumns: ["id"]
          },
        ]
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          p256dh: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          p256dh: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          p256dh?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "push_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      question_flows: {
        Row: {
          category_id: string
          created_at: string
          id: string
          published: boolean
          schema: Json
          version: number
        }
        Insert: {
          category_id: string
          created_at?: string
          id?: string
          published?: boolean
          schema: Json
          version?: number
        }
        Update: {
          category_id?: string
          created_at?: string
          id?: string
          published?: boolean
          schema?: Json
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "question_flows_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          admin_note: string | null
          created_at: string
          detail: string | null
          id: string
          reason: string
          reporter_id: string | null
          resolved_at: string | null
          status: string
          target_id: string
          target_type: string
        }
        Insert: {
          admin_note?: string | null
          created_at?: string
          detail?: string | null
          id?: string
          reason: string
          reporter_id?: string | null
          resolved_at?: string | null
          status?: string
          target_id: string
          target_type: string
        }
        Update: {
          admin_note?: string | null
          created_at?: string
          detail?: string | null
          id?: string
          reason?: string
          reporter_id?: string | null
          resolved_at?: string | null
          status?: string
          target_id?: string
          target_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          author_id: string | null
          business_id: string
          comment: string | null
          created_at: string
          id: string
          is_demo: boolean
          rating: number
          replied_at: string | null
          reply: string | null
          request_id: string | null
        }
        Insert: {
          author_id?: string | null
          business_id: string
          comment?: string | null
          created_at?: string
          id?: string
          is_demo?: boolean
          rating: number
          replied_at?: string | null
          reply?: string | null
          request_id?: string | null
        }
        Update: {
          author_id?: string | null
          business_id?: string
          comment?: string | null
          created_at?: string
          id?: string
          is_demo?: boolean
          rating?: number
          replied_at?: string | null
          reply?: string | null
          request_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_business_id_fkey"
            columns: ["business_id"]
            isOneToOne: false
            referencedRelation: "businesses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "service_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      service_categories: {
        Row: {
          active: boolean
          auto_dispatch: boolean
          created_at: string
          description: string | null
          icon: string | null
          id: string
          max_providers: number
          name: string
          notify_pool_size: number
          parent_id: string | null
          popular: boolean
          search_norm: string | null
          slug: string
          sort: number
          synonyms: string[]
        }
        Insert: {
          active?: boolean
          auto_dispatch?: boolean
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          max_providers?: number
          name: string
          notify_pool_size?: number
          parent_id?: string | null
          popular?: boolean
          search_norm?: string | null
          slug: string
          sort?: number
          synonyms?: string[]
        }
        Update: {
          active?: boolean
          auto_dispatch?: boolean
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          max_providers?: number
          name?: string
          notify_pool_size?: number
          parent_id?: string | null
          popular?: boolean
          search_norm?: string | null
          slug?: string
          sort?: number
          synonyms?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "service_categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      service_requests: {
        Row: {
          accepted_count: number
          address_note: string | null
          answers: Json
          category_id: string
          closed_at: string | null
          created_at: string
          customer_id: string | null
          dispatch_note: string | null
          flow_id: string | null
          hide_phone: boolean
          hired_business_id: string | null
          id: string
          is_demo: boolean
          max_providers: number
          neighbourhood_id: string | null
          note: string | null
          photos: string[]
          public_code: string
          status: string
          updated_at: string
          when_date: string | null
          when_type: string
        }
        Insert: {
          accepted_count?: number
          address_note?: string | null
          answers?: Json
          category_id: string
          closed_at?: string | null
          created_at?: string
          customer_id?: string | null
          dispatch_note?: string | null
          flow_id?: string | null
          hide_phone?: boolean
          hired_business_id?: string | null
          id?: string
          is_demo?: boolean
          max_providers?: number
          neighbourhood_id?: string | null
          note?: string | null
          photos?: string[]
          public_code: string
          status?: string
          updated_at?: string
          when_date?: string | null
          when_type?: string
        }
        Update: {
          accepted_count?: number
          address_note?: string | null
          answers?: Json
          category_id?: string
          closed_at?: string | null
          created_at?: string
          customer_id?: string | null
          dispatch_note?: string | null
          flow_id?: string | null
          hide_phone?: boolean
          hired_business_id?: string | null
          id?: string
          is_demo?: boolean
          max_providers?: number
          neighbourhood_id?: string | null
          note?: string | null
          photos?: string[]
          public_code?: string
          status?: string
          updated_at?: string
          when_date?: string | null
          when_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_requests_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_requests_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_requests_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_requests_flow_id_fkey"
            columns: ["flow_id"]
            isOneToOne: false
            referencedRelation: "question_flows"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_requests_hired_business_id_fkey"
            columns: ["hired_business_id"]
            isOneToOne: false
            referencedRelation: "businesses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_requests_neighbourhood_id_fkey"
            columns: ["neighbourhood_id"]
            isOneToOne: false
            referencedRelation: "neighbourhoods"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      my_leads: {
        Row: {
          accepted_at: string | null
          accepted_count: number | null
          business_id: string | null
          category_icon: string | null
          category_id: string | null
          category_name: string | null
          category_slug: string | null
          created_at: string | null
          has_note: boolean | null
          id: string | null
          max_providers: number | null
          neighbourhood_id: string | null
          neighbourhood_name: string | null
          offer_note: string | null
          offer_price_try: number | null
          photo_count: number | null
          request_created_at: string | null
          request_id: string | null
          request_status: string | null
          seen_at: string | null
          status: string | null
          wave_no: number | null
          when_date: string | null
          when_type: string | null
        }
        Relationships: [
          {
            foreignKeyName: "leads_business_id_fkey"
            columns: ["business_id"]
            isOneToOne: false
            referencedRelation: "businesses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "service_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_requests_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_requests_neighbourhood_id_fkey"
            columns: ["neighbourhood_id"]
            isOneToOne: false
            referencedRelation: "neighbourhoods"
            referencedColumns: ["id"]
          },
        ]
      }
      public_profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          display_name: string | null
          id: string | null
          neighbourhood_id: string | null
          phone_verified: boolean | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          display_name?: never
          id?: string | null
          neighbourhood_id?: string | null
          phone_verified?: never
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          display_name?: never
          id?: string | null
          neighbourhood_id?: string | null
          phone_verified?: never
        }
        Relationships: [
          {
            foreignKeyName: "profiles_neighbourhood_id_fkey"
            columns: ["neighbourhood_id"]
            isOneToOne: false
            referencedRelation: "neighbourhoods"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      accept_lead: {
        Args: {
          p_lead_id: string
          p_offer_note?: string
          p_offer_price?: number
        }
        Returns: Json
      }
      admin_clear_demo_data: { Args: { p_scopes: string[] }; Returns: Json }
      admin_data_health: { Args: never; Returns: Json }
      admin_publish_flow: {
        Args: { p_category_id: string; p_schema: Json }
        Returns: Json
      }
      admin_request_candidates: {
        Args: { p_request_id: string }
        Returns: {
          area_match: boolean
          business_id: string
          business_name: string
          score: number
        }[]
      }
      admin_review_business: {
        Args: { p_approve: boolean; p_business_id: string; p_reason?: string }
        Returns: Json
      }
      admin_review_listing: {
        Args: { p_approve: boolean; p_listing_id: string; p_reason?: string }
        Returns: Json
      }
      apply_business: {
        Args: {
          p_address?: string
          p_category_label?: string
          p_cover_url?: string
          p_description?: string
          p_kinds: string[]
          p_lat?: number
          p_lng?: number
          p_logo_url?: string
          p_name: string
          p_neighbourhood_id?: string
          p_phone?: string
          p_service_area_ids?: string[]
          p_service_category_ids?: string[]
          p_working_hours?: Json
        }
        Returns: Json
      }
      business_is_public: { Args: { p_business_id: string }; Returns: boolean }
      business_panel_stats: { Args: never; Returns: Json }
      close_request: {
        Args: { p_code: string; p_hired_business_id?: string }
        Returns: Json
      }
      customer_remove_lead: { Args: { p_lead_id: string }; Returns: Json }
      decline_lead: { Args: { p_lead_id: string }; Returns: Json }
      delete_my_account: { Args: never; Returns: Json }
      dispatch_request: {
        Args: {
          p_business_ids?: string[]
          p_request_id: string
          p_wave?: number
        }
        Returns: Json
      }
      duty_pharmacies_for_day: {
        Args: { p_date: string; p_lat?: number; p_lng?: number }
        Returns: {
          address: string
          distance_m: number
          duty_end: string
          duty_id: string
          duty_start: string
          fetched_at: string
          lat: number
          lng: number
          name: string
          neighbourhood_id: string
          neighbourhood_name: string
          note: string
          phone: string
          poi_id: string
          slug: string
          source: string
        }[]
      }
      duty_pharmacies_now: {
        Args: { p_lat?: number; p_lng?: number }
        Returns: {
          address: string
          distance_m: number
          duty_end: string
          duty_id: string
          duty_start: string
          fetched_at: string
          lat: number
          lng: number
          name: string
          neighbourhood_id: string
          neighbourhood_name: string
          note: string
          phone: string
          poi_id: string
          slug: string
          source: string
        }[]
      }
      expire_listings: { Args: never; Returns: number }
      get_demo_otp: { Args: { p_phone: string }; Returns: string }
      get_lead_detail: { Args: { p_lead_id: string }; Returns: Json }
      get_request_for_customer: { Args: { p_code: string }; Returns: Json }
      global_search: { Args: { p_limit?: number; p_q: string }; Returns: Json }
      increment_listing_view: {
        Args: { p_listing_id: string }
        Returns: undefined
      }
      is_admin: { Args: never; Returns: boolean }
      log_contact_event: {
        Args: { p_event: string; p_subject_id: string; p_subject_type: string }
        Returns: undefined
      }
      mark_notifications_read: { Args: { p_ids?: string[] }; Returns: number }
      my_lead_extras: {
        Args: { p_lead_ids: string[] }
        Returns: {
          hired: boolean
          lead_id: string
          summary: string
        }[]
      }
      nearby_pois: {
        Args: {
          p_kind?: string
          p_lat?: number
          p_limit?: number
          p_lng?: number
          p_radius_m?: number
        }
        Returns: {
          address: string
          details: Json
          distance_m: number
          id: string
          kind: string
          lat: number
          license: string
          lng: number
          name: string
          neighbourhood_id: string
          neighbourhood_name: string
          phone: string
          slug: string
          source: string
          updated_at: string
        }[]
      }
      neighbourhood_for_point: {
        Args: { p_lat: number; p_lng: number }
        Returns: {
          district: string
          id: string
          method: string
          name: string
          slug: string
        }[]
      }
      owns_business: { Args: { p_business_id: string }; Returns: boolean }
      owns_listing: { Args: { p_listing_id: string }; Returns: boolean }
      renew_listing: { Args: { p_listing_id: string }; Returns: Json }
      reply_review: {
        Args: { p_reply: string; p_review_id: string }
        Returns: Json
      }
      reveal_listing_phone: { Args: { p_listing_id: string }; Returns: Json }
      roll_demo_duty: { Args: never; Returns: number }
      search_listings: {
        Args: {
          p_category_id?: string
          p_max_price?: number
          p_min_price?: number
          p_neighbourhood_id?: string
          p_q?: string
          p_sort?: string
          p_type?: string
          p_work_type?: string
        }
        Returns: {
          attributes: Json
          business_id: string | null
          call_count: number
          category_id: string
          created_at: string
          description: string | null
          expires_at: string
          flags: string[]
          id: string
          is_demo: boolean
          job_benefits: string[]
          job_experience: string | null
          job_location_label: string | null
          job_salary_hidden: boolean
          job_salary_max: number | null
          job_salary_min: number | null
          job_work_type: string | null
          neighbourhood_id: string | null
          owner_id: string
          price_try: number | null
          published_at: string | null
          rejection_reason: string | null
          search_norm: string | null
          search_tsv: unknown
          status: string
          title: string
          type: string
          updated_at: string
          view_count: number
        }[]
        SetofOptions: {
          from: "*"
          to: "listings"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      send_sms_hook: { Args: { event: Json }; Returns: Json }
      short_name: { Args: { p_full_name: string }; Returns: string }
      submit_review: {
        Args: {
          p_business_id: string
          p_comment?: string
          p_rating: number
          p_request_code: string
        }
        Returns: Json
      }
      submit_service_request: {
        Args: {
          p_address_note?: string
          p_answers: Json
          p_category_id: string
          p_hide_phone?: boolean
          p_neighbourhood_id: string
          p_note?: string
          p_photos?: string[]
          p_when_date?: string
          p_when_type?: string
        }
        Returns: Json
      }
      tr_match: { Args: { p_norm: string; p_q: string }; Returns: boolean }
      tr_norm: { Args: { t: string }; Returns: string }
      tr_slug: { Args: { t: string }; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
